### ISSUE TITLE
TypeError: Cannot read property 'lightYellow' of undefined

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [henrikdahl/hyper-tabs-enhanced#19]
When installing this plugin, I get the error `TypeError: Cannot read property 'lightYellow' of undefined`:

<img width="532" alt="screen shot 2017-05-23 at 1 19 24 am" src="https://cloud.githubusercontent.com/assets/200/26340896/8cc56d08-3f56-11e7-903b-baca2cac97b6.png">

Worse, thereafter, I cannot successfully open Hyper; when trying to, no window appears, and Hyper's menubar never loads:

<img width="244" alt="screen shot 2017-05-23 at 1 21 15 am" src="https://cloud.githubusercontent.com/assets/200/26340926/c25a25e4-3f56-11e7-9d58-129780abc017.png">

If I launch it from the Terminal, I get this on stdout:

```
> /Applications/Hyper.app/Contents/MacOS/Hyper
running in prod mode
electron will open file:///Applications/Hyper.app/Contents/Resources/app/index.html
Error while loading devtools extensions TypeError: Cannot read property 'lightYellow' of undefined
    at Object.exports.decorateConfig (/Users/ec/.hyper_plugins/node_modules/hyper-tabs-enhanced/index.js:19:37)
    at modules.forEach.plugin (/Applications/Hyper.app/Contents/Resources/app/plugins.js:345:30)
    at Array.forEach (native)
    at decorateObject (/Applications/Hyper.app/Contents/Resources/app/plugins.js:343:11)
    at Object.exports.getDecoratedConfig (/Applications/Hyper.app/Contents/Resources/app/plugins.js:367:10)
    at createWindow (/Applications/Hyper.app/Contents/Resources/app/index.js:107:23)
    at installDevExtensions.then (/Applications/Hyper.app/Contents/Resources/app/index.js:379:3)
```

**Comment by ELLIOTTCABLE** [comment]
Okay, turns out this happens if the existing config doesn't have a `colours` array (I use a theme, and have deleted all the unchanged-from-default values from my configuration.)

So, it looks like [index.js](https://github.com/henrikdahl/hyper-tabs-enhanced/blob/master/index.js#L19) needs to access the default value in Hyper, in the case of the `config` object missing the defaults!

**Comment by henrikruscon** [comment]
Just fixed this in latest commit ✌️

**Comment by ELLIOTTCABLE** [comment]
<3
