### ISSUE TITLE
trafficButtons seem broken

### ISSUE THREAD

**Issue by QuentinRoy** [henrikdahl/hyper-tabs-enhanced#35]
Whatever I do, I cannot make Mac OS button appears. Since I am often putting my terminal in full screen mode, losing the button is an issue for me.

**Comment by jcklpe** [comment]
@QuentinRoy  I seem to be having a similar problem. Are you on Hyper 2 and have you checked for a yarn error? I get this yarn error which seems to indicate something is broken with importing the icons:

```
Arguments: 
  C:\Users\David\AppData\Local\hyper\app-2.0.0\Hyper.exe C:\Users\David\AppData\Local\hyper\app-2.0.0\resources\bin\yarn-standalone.js install --no-emoji --no-lockfile --cache-folder C:\Users\David\.hyper_plugins\cache

PATH: 
  C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Python37\Scripts\;C:\Python37\;C:\ProgramData\Boxstarter;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\Git LFS;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Users\David\AppData\Local\Microsoft\WindowsApps;C:\Users\David\AppData\Local\Pandoc\;C:\Users\David\AppData\Roaming\npm;C:\Users\David\AppData\Local\Yarn\bin;C:\Users\David\AppData\Local\hyper\app-2.0.0\resources\bin

Yarn version: 
  1.3.2

Node version: 
  8.2.1

Platform: 
  win32 x64

npm manifest: 
  {
    "name": "hyper-plugins",
    "description": "Auto-generated from `~/.hyper.js`!",
    "private": true,
    "version": "0.0.1",
    "repository": "zeit/hyper",
    "license": "MIT",
    "homepage": "https://hyper.is",
    "dependencies": {
      "hyperterm-tabs": "latest",
      "hypertheme": "latest",
      "hyperterm-blink": "latest",
      "hyperborder": "latest",
      "hyperterm-icons": "latest",
      "hyperterm-paste": "latest",
      "hyperterm-alternatescroll": "latest",
      "hyperterm-bold-tab": "latest",
      "hyperterm-dibdabs": "latest",
      "hyperlinks": "latest",
      "hyper-alt-click": "latest",
      "hyper-match": "latest",
      "hyperterm-crosshair": "latest",
      "hyper-autohide-tabs": "latest",
      "hyper-tabs-enhanced": "latest",
      "hyper-pane": "latest",
      "hyper-hover-header": "latest",
      "hyper-background": "latest",
      "gitrocket": "latest",
      "space-pull": "latest",
      "hyperatompunk": "latest"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: https://registry.yarnpkg.com/hyperterm-icons: Not found
      at Request.params.callback [as _callback] (C:\Users\David\AppData\Local\hyper\app-2.0.0\resources\bin\yarn-standalone.js:65368:18)
      at Request.self.callback (C:\Users\David\AppData\Local\hyper\app-2.0.0\resources\bin\yarn-standalone.js:121753:22)
      at emitTwo (events.js:125:13)
      at Request.emit (events.js:213:7)
      at Request.<anonymous> (C:\Users\David\AppData\Local\hyper\app-2.0.0\resources\bin\yarn-standalone.js:122736:10)
      at emitOne (events.js:115:13)
      at Request.emit (events.js:210:7)
      at IncomingMessage.<anonymous> (C:\Users\David\AppData\Local\hyper\app-2.0.0\resources\bin\yarn-standalone.js:122656:12)
      at Object.onceWrapper (events.js:314:30)
      at emitNone (events.js:110:20)
```

**Comment by QuentinRoy** [comment]
Hum. No. I haven't used yarn  to install hyper 2 or any of its dependencies (at least directly). I am not sure when you got this error.

**Comment by jcklpe** [comment]
@QuentinRoy 

Neither have I. But some of the plugins do. Since this is the only plugin that I can think of that would be pulling in a package called "hyperterm-icons" my guess is that may be related to the issue you are having. Could be way off base though.

**Comment by mediter** [comment]
same issue here.

Hyper 2.0.0 (stable) installation via direct download

macOS Mojave

**Comment by simonl65** [comment]
Same issue here on Mojave

**Comment by mastrauckas** [comment]
Not only can I not get `trafficButtons` to work, I can't seem to get any of the settings to work.

**Comment by ghost** [comment]
@mastrauckas 

Full on edit:

Make sure you actually place the settings before the closing `},` of `config: {`

```
module.exports = {
  config: {
	updateChannel: 'stable',
	
    fontSize: 12,
    fontFamily: 'Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: 'normal',
	fontWeightBold: 'bold',
	
    cursorColor: 'rgba(248,28,229,0.8)',
    cursorAccentColor: '#000',
    cursorShape: 'BLOCK',
    cursorBlink: true,

    foregroundColor: '#fff',
    backgroundColor: '#000',
    selectionColor: 'rgba(248,28,229,0.3)',
	borderColor: '#333',
	colors: {
		black: '#000000',
		red: '#C51E14',
		green: '#1DC121',
		yellow: '#C7C329',
		blue: '#0A2FC4',
		magenta: '#C839C5',
		cyan: '#20C5C6',
		white: '#C7C7C7',
		lightBlack: '#686868',
		lightRed: '#FD6F6B',
		lightGreen: '#67F86F',
		lightYellow: '#FFFA72',
		lightBlue: '#6A76FB',
		lightMagenta: '#FD7CFC',
		lightCyan: '#68FDFE',
		lightWhite: '#FFFFFF'
	  },

    css: '',
	termCSS: '',
	
    showHamburgerMenu: '',
	showWindowControls: '',

    padding: '12px 20px',
    
	shell: '',
	shellArgs: ['--login'],

	env: {},

	bell: false,
	
	copyOnSelect: true,
	
	defaultSSHApp: true,

	// Settings for plugins
    hyperBorder: {
      borderWidth: '4px',
      animate: true
    },
    hyperSpotify: {
      position: 'bottom',
      margin: 'double'
    },
    hyperTabs: {
      trafficButtons: true,
      border: true,
      tabIconsColored: true
    },
  }, // Closes Config

  plugins: [
    "hyper-chesterish",
    "hyper-tabs-enhanced",
    "hyper-spotify",
    "hyper-statusline",
    "hyperborder"
  ]
};
```

This is what my config file looks like now (w/o the comments)
