### ISSUE TITLE
Icons seem to be broken in Hyper 2

### ISSUE THREAD

**Issue by jcklpe** [henrikdahl/hyper-tabs-enhanced#36]
Hey just thought I should let you know. I did a clean install of Hyper 2 on Windows WSL and it seems that icons are not working. When I have hyper-tabs turned on with all defaults it throws a yarn error. 

Here's my yarn error. The hyperterm icons issue is mentioned at the bottom. 

```
Arguments: 
  C:\Users\David\AppData\Local\hyper\app-2.0.0\Hyper.exe C:\Users\David\AppData\Local\hyper\app-2.0.0\resources\bin\yarn-standalone.js install --no-emoji --no-lockfile --cache-folder C:\Users\David\.hyper_plugins\cache

PATH: 
  C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Python37\Scripts\;C:\Python37\;C:\ProgramData\Boxstarter;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft VS Code\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Git\cmd;C:\Program Files\Git LFS;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin\;C:\Users\David\AppData\Local\Microsoft\WindowsApps;C:\Users\David\AppData\Local\Pandoc\;C:\Users\David\AppData\Roaming\npm;C:\Users\David\AppData\Local\Yarn\bin;C:\Users\David\AppData\Local\hyper\app-2.0.0\resources\bin

Yarn version: 
  1.3.2

Node version: 
  8.2.1

Platform: 
  win32 x64

npm manifest: 
  {
    "name": "hyper-plugins",
    "description": "Auto-generated from `~/.hyper.js`!",
    "private": true,
    "version": "0.0.1",
    "repository": "zeit/hyper",
    "license": "MIT",
    "homepage": "https://hyper.is",
    "dependencies": {
      "hyperterm-tabs": "latest",
      "hypertheme": "latest",
      "hyperterm-blink": "latest",
      "hyperborder": "latest",
      "hyperterm-icons": "latest",
      "hyperterm-paste": "latest",
      "hyperterm-alternatescroll": "latest",
      "hyperterm-bold-tab": "latest",
      "hyperterm-dibdabs": "latest",
      "hyperlinks": "latest",
      "hyper-alt-click": "latest",
      "hyper-match": "latest",
      "hyperterm-crosshair": "latest",
      "hyper-autohide-tabs": "latest",
      "hyper-tabs-enhanced": "latest",
      "hyper-pane": "latest",
      "hyper-hover-header": "latest",
      "hyper-background": "latest",
      "gitrocket": "latest",
      "space-pull": "latest",
      "hyperatompunk": "latest"
    }
  }

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: https://registry.yarnpkg.com/hyperterm-icons: Not found
      at Request.params.callback [as _callback] (C:\Users\David\AppData\Local\hyper\app-2.0.0\resources\bin\yarn-standalone.js:65368:18)
      at Request.self.callback (C:\Users\David\AppData\Local\hyper\app-2.0.0\resources\bin\yarn-standalone.js:121753:22)
      at emitTwo (events.js:125:13)
      at Request.emit (events.js:213:7)
      at Request.<anonymous> (C:\Users\David\AppData\Local\hyper\app-2.0.0\resources\bin\yarn-standalone.js:122736:10)
      at emitOne (events.js:115:13)
      at Request.emit (events.js:210:7)
      at IncomingMessage.<anonymous> (C:\Users\David\AppData\Local\hyper\app-2.0.0\resources\bin\yarn-standalone.js:122656:12)
      at Object.onceWrapper (events.js:314:30)
      at emitNone (events.js:110:20)
```

**Comment by jcklpe** [comment]
This issue has resolved itself after deleting and rebuilding my hyperplugins folder.
